version: "3.9"

services:
  noah-server:
    build: .
    container_name: noah-server
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - E:/noah:/data  # 로컬 파일 저장소
    restart: unless-stopped
